export const mockPackages = [
  {
    id: 1,
    title: "مالديف الأحلام",
    titleEn: "Maldives Dream Escape",
    description: "استمتع بأجمل الشواطئ البيضاء والمياه الفيروزية في جزر المالديف",
    descriptionEn: "Enjoy the most beautiful white beaches and turquoise waters in the Maldives",
    destination: "المالديف",
    destinationEn: "Maldives",
    duration: "7 أيام / 6 ليالي",
    durationEn: "7 Days / 6 Nights",
    price: 15000,
    originalPrice: 19000,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 342,
    category: "beach",
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800",
    includedTrips: [1, 2],
    gallery: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800",
      "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=800"
    ],
    includes: ["طيران ذهاب وإياب", "فندق 5 نجوم", "إفطار يومي", "جولات بحرية"],
    includesEn: ["Round-trip flights", "5-star hotel", "Daily breakfast", "Boat tours"],
    maxGroupSize: 12,
    featured: true,
    badge: "الأكثر مبيعاً",
    badgeEn: "Best Seller",
    itinerary: [
      { day: 1, title: "الوصول والاستقبال", desc: "استقبال في المطار والانتقال السريع بالقارب السريع إلى المنتجع والفندق المائي." },
      { day: 2, title: "جولة بحرية وغطس", desc: "رحلة بحرية في الصباح الباكر، واستكشاف الشعاب المرجانية وأسماك المالديف الساحرة." },
      { day: 3, title: "يوم حر واسترخاء", desc: "يوم حر للاستمتاع بخدمات السبا في المنتجع، والمرافق الترفيهية الفاخرة." },
      { day: 4, title: "صيد ليلي وعشاء رومانسي", desc: "رحلة صيد عند الغروب، تليها عشاء رومانسي على شاطئ البحر." },
      { day: 5, title: "جولة الغواصة المالديفية", desc: "استكشاف أعماق المحيط عبر غواصة آمنة لمشاهدة الحياة البحرية الفريدة." },
      { day: 6, title: "تسوق ومغادرة", desc: "جولة حرة لشراء الهدايا التذكارية، ثم الانتقال للمطار." }
    ],
    itineraryEn: [
      { day: 1, title: "Arrival & Welcome", desc: "Airport pickup and speedboat transfer to the resort and overwater villa." },
      { day: 2, title: "Boat Tour & Snorkeling", desc: "Morning boat trip exploring coral reefs and the enchanting marine life of Maldives." },
      { day: 3, title: "Free Day & Relaxation", desc: "Free day to enjoy spa services and premium recreational facilities." },
      { day: 4, title: "Night Fishing & Romantic Dinner", desc: "Sunset fishing trip followed by a romantic beach dinner." },
      { day: 5, title: "Submarine Tour", desc: "Explore the ocean depths in a safe submarine to see unique marine life." },
      { day: 6, title: "Shopping & Departure", desc: "Free time for souvenir shopping, then transfer to the airport." }
    ]
  },
  {
    id: 2,
    title: "سحر الطبيعة السويسرية",
    titleEn: "Swiss Alpine Magic",
    description: "تجول بين جبال الألب الخلابة واستمتع بالهواء النقي والمناظر الساحرة",
    descriptionEn: "Stroll through the stunning Alps and enjoy fresh air and breathtaking views",
    destination: "سويسرا",
    destinationEn: "Switzerland",
    duration: "10 أيام / 9 ليالي",
    durationEn: "10 Days / 9 Nights",
    price: 22000,
    originalPrice: 28000,
    currency: "EGP",
    rating: 4.8,
    reviewCount: 215,
    category: "mountain",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    includedTrips: [2, 3],
    gallery: [
      "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800"
    ],
    includes: ["طيران", "فندق 4 نجوم", "تذاكر القطارات", "مرشد سياحي"],
    includesEn: ["Flights", "4-star hotel", "Train tickets", "Tour guide"],
    maxGroupSize: 15,
    featured: true,
    badge: "عرض محدود",
    badgeEn: "Limited Offer",
    itinerary: [
      { day: 1, title: "الوصول إلى زيورخ", desc: "جولة في مدينة زيورخ الجميلة والتعرف على معالمها التاريخية." },
      { day: 2, title: "قمة جبل تيتليس", desc: "الصعود بالتلفريك لأعلى قمم الجليد وتجربة الجسر المعلق." },
      { day: 3, title: "شلالات الراين", desc: "زيارة أضخم شلالات أوروبا والاستمتاع بجولة بالقارب." }
    ],
    itineraryEn: [
      { day: 1, title: "Arrival in Zurich", desc: "Tour of beautiful Zurich and its historic landmarks." },
      { day: 2, title: "Mount Titlis Summit", desc: "Cable car ascent to the highest ice peaks and the suspension bridge." },
      { day: 3, title: "Rhine Falls", desc: "Visit Europe's largest waterfalls and enjoy a boat tour." }
    ]
  },
  {
    id: 3,
    title: "روما الخالدة",
    titleEn: "Eternal Rome",
    description: "اكتشف عراقة التاريخ الروماني وتذوق أشهى المأكولات الإيطالية",
    descriptionEn: "Discover the richness of Roman history and taste the finest Italian cuisine",
    destination: "إيطاليا",
    destinationEn: "Italy",
    duration: "8 أيام / 7 ليالي",
    durationEn: "8 Days / 7 Nights",
    price: 12000,
    originalPrice: 15000,
    currency: "EGP",
    rating: 4.7,
    reviewCount: 489,
    category: "city",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    includes: ["طيران", "فندق 4 نجوم", "جولات ثقافية", "وجبات مختارة"],
    includesEn: ["Flights", "4-star hotel", "Cultural tours", "Selected meals"],
    maxGroupSize: 20,
    featured: true,
    badge: null,
    badgeEn: null,
  },
  {
    id: 4,
    title: "مغامرات كينيا البرية",
    titleEn: "Kenya Wild Safari",
    description: "عش تجربة السفاري الأفريقي ورحلة لا تُنسى مع أعظم الحيوانات",
    descriptionEn: "Experience the African safari and an unforgettable journey with magnificent wildlife",
    destination: "كينيا",
    destinationEn: "Kenya",
    duration: "9 أيام / 8 ليالي",
    durationEn: "9 Days / 8 Nights",
    price: 18000,
    originalPrice: 23000,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 178,
    category: "adventure",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800",
    includes: ["طيران", "لودج فاخر", "رحلات سفاري يومية", "مرشد متخصص"],
    includesEn: ["Flights", "Luxury lodge", "Daily safaris", "Specialist guide"],
    maxGroupSize: 10,
    featured: false,
    badge: "مغامرة لا تُنسى",
    badgeEn: "Unforgettable Adventure",
  },
  {
    id: 5,
    title: "باريس رومانسية",
    titleEn: "Romantic Paris",
    description: "مدينة النور والحب في رحلة لا تُنسى بين معالم باريس الشهيرة",
    descriptionEn: "The city of light and love in an unforgettable journey through famous Parisian landmarks",
    destination: "فرنسا",
    destinationEn: "France",
    duration: "6 أيام / 5 ليالي",
    durationEn: "6 Days / 5 Nights",
    price: 13500,
    originalPrice: 17000,
    currency: "EGP",
    rating: 4.8,
    reviewCount: 623,
    category: "city",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    includes: ["طيران", "فندق بوتيك", "رحلة نهر السين", "زيارة برج إيفل"],
    includesEn: ["Flights", "Boutique hotel", "Seine river cruise", "Eiffel Tower visit"],
    maxGroupSize: 16,
    featured: false,
    badge: "رومانسي",
    badgeEn: "Romantic",
  },
  {
    id: 6,
    title: "بالي الروحانية",
    titleEn: "Spiritual Bali",
    description: "جزيرة الآلهة حيث الطبيعة الخلابة والثقافة الآسيوية المميزة",
    descriptionEn: "Island of the Gods where stunning nature meets unique Asian culture",
    destination: "إندونيسيا",
    destinationEn: "Indonesia",
    duration: "8 أيام / 7 ليالي",
    durationEn: "8 Days / 7 Nights",
    price: 11000,
    originalPrice: 14000,
    currency: "EGP",
    rating: 4.7,
    reviewCount: 387,
    category: "beach",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    includes: ["طيران", "فيلا خاصة", "جلسات يوغا", "جولات المعابد"],
    includesEn: ["Flights", "Private villa", "Yoga sessions", "Temple tours"],
    maxGroupSize: 14,
    featured: false,
    badge: null,
    badgeEn: null,
  },
  {
    id: 7,
    title: "نيبال تحدي إيفرست",
    titleEn: "Nepal Everest Trek",
    description: "تسلق لأعلى قمة في العالم وعش مغامرة التريكينج في جبال الهيمالايا",
    descriptionEn: "Climb the world's highest peak and experience trekking in the Himalayas",
    destination: "نيبال",
    destinationEn: "Nepal",
    duration: "14 أيام / 13 ليالي",
    durationEn: "14 Days / 13 Nights",
    price: 25000,
    originalPrice: 32000,
    currency: "EGP",
    rating: 5.0,
    reviewCount: 95,
    category: "adventure",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800",
    includedTrips: [1, 3],
    gallery: [
      "https://images.unsplash.com/photo-1522083115901-bc11d2449b29?w=800"
    ],
    includes: ["طيران", "إقامة المخيم", "معدات التسلق", "مرشد جبلي معتمد"],
    includesEn: ["Flights", "Camping accommodation", "Climbing equipment", "Certified mountain guide"],
    maxGroupSize: 8,
    featured: false,
    badge: "للمغامرين فقط",
    badgeEn: "Adventurers Only",
  },
  {
    id: 8,
    title: "اليابان في الربيع",
    titleEn: "Japan Cherry Blossom",
    description: "شاهد زهور الكرز الوردية واكتشف مزيج الحداثة والتراث الياباني",
    descriptionEn: "Witness pink cherry blossoms and discover Japan's blend of modernity and tradition",
    destination: "اليابان",
    destinationEn: "Japan",
    duration: "11 أيام / 10 ليالي",
    durationEn: "11 Days / 10 Nights",
    price: 27000,
    originalPrice: 33000,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 256,
    category: "city",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
    includes: ["طيران", "فندق تقليدي (ريوكان)", "JR Pass", "جولات ثقافية"],
    includesEn: ["Flights", "Traditional Ryokan hotel", "JR Pass", "Cultural tours"],
    maxGroupSize: 18,
    featured: false,
    badge: "موسمي",
    badgeEn: "Seasonal",
  },
];

export const mockCategories = [
  { id: "all", label: "الكل", labelEn: "All", icon: "Globe" },
  { id: "beach", label: "شواطئ", labelEn: "Beaches", icon: "Waves" },
  { id: "mountain", label: "جبال", labelEn: "Mountains", icon: "Mountain" },
  { id: "city", label: "مدن", labelEn: "Cities", icon: "Building" },
  { id: "adventure", label: "مغامرات", labelEn: "Adventure", icon: "Compass" },
];

export const mockStats = {
  destinations: 120,
  travelers: 50000,
  years: 15,
  rating: 4.9,
};
