export const mockPackages = [
  {
    id: 1,
    title: "Maldives Dream Escape",
    description: "Enjoy the most beautiful white beaches and turquoise waters in the Maldives",
    destination: "Maldives",
    duration: "7 Days / 6 Nights",
    price: 15000,
    originalPrice: 19000,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 342,
    category: "beach",
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800",
    includedTrips: [1, 2],
    gallery: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800",
      "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=800"
    ],
    includes: ["Round-trip flights", "5-star hotel", "Daily breakfast", "Boat tours"],
    maxGroupSize: 12,
    featured: true,
    badge: "Best Seller",
    itinerary: [
      { day: 1, title: "Arrival & Welcome", desc: "Airport pickup and speedboat transfer to the resort and overwater villa." },
      { day: 2, title: "Boat Tour & Snorkeling", desc: "Morning boat trip exploring coral reefs and the enchanting marine life of Maldives." },
      { day: 3, title: "Free Day & Relaxation", desc: "Free day to enjoy spa services and premium recreational facilities." },
      { day: 4, title: "Night Fishing & Romantic Dinner", desc: "Sunset fishing trip followed by a romantic beach dinner." },
      { day: 5, title: "Submarine Tour", desc: "Explore the ocean depths in a safe submarine to see unique marine life." },
      { day: 6, title: "Shopping & Departure", desc: "Free time for souvenir shopping, then transfer to the airport." }
    ]
  },
  {
    id: 2,
    title: "Swiss Alpine Magic",
    description: "Stroll through the stunning Alps and enjoy fresh air and breathtaking views",
    destination: "Switzerland",
    duration: "10 Days / 9 Nights",
    price: 22000,
    originalPrice: 28000,
    currency: "EGP",
    rating: 4.8,
    reviewCount: 215,
    category: "mountain",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    includedTrips: [2, 3],
    gallery: [
      "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800"
    ],
    includes: ["Flights", "4-star hotel", "Train tickets", "Tour guide"],
    maxGroupSize: 15,
    featured: true,
    badge: "Limited Offer",
    itinerary: [
      { day: 1, title: "Arrival in Zurich", desc: "Tour of beautiful Zurich and its historic landmarks." },
      { day: 2, title: "Mount Titlis Summit", desc: "Cable car ascent to the highest ice peaks and the suspension bridge." },
      { day: 3, title: "Rhine Falls", desc: "Visit Europe's largest waterfalls and enjoy a boat tour." }
    ]
  },
  {
    id: 3,
    title: "Eternal Rome",
    description: "Discover the richness of Roman history and taste the finest Italian cuisine",
    destination: "Italy",
    duration: "8 Days / 7 Nights",
    price: 12000,
    originalPrice: 15000,
    currency: "EGP",
    rating: 4.7,
    reviewCount: 489,
    category: "city",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    includes: ["Flights", "4-star hotel", "Cultural tours", "Selected meals"],
    maxGroupSize: 20,
    featured: true,
    badge: null,
  },
  {
    id: 4,
    title: "Kenya Wild Safari",
    description: "Experience the African safari and an unforgettable journey with magnificent wildlife",
    destination: "Kenya",
    duration: "9 Days / 8 Nights",
    price: 18000,
    originalPrice: 23000,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 178,
    category: "adventure",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800",
    includes: ["Flights", "Luxury lodge", "Daily safaris", "Specialist guide"],
    maxGroupSize: 10,
    featured: false,
    badge: "Unforgettable Adventure",
  },
  {
    id: 5,
    title: "Romantic Paris",
    description: "The city of light and love in an unforgettable journey through famous Parisian landmarks",
    destination: "France",
    duration: "6 Days / 5 Nights",
    price: 13500,
    originalPrice: 17000,
    currency: "EGP",
    rating: 4.8,
    reviewCount: 623,
    category: "city",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    includes: ["Flights", "Boutique hotel", "Seine river cruise", "Eiffel Tower visit"],
    maxGroupSize: 16,
    featured: false,
    badge: "Romantic",
  },
  {
    id: 6,
    title: "Spiritual Bali",
    description: "Island of the Gods where stunning nature meets unique Asian culture",
    destination: "Indonesia",
    duration: "8 Days / 7 Nights",
    price: 11000,
    originalPrice: 14000,
    currency: "EGP",
    rating: 4.7,
    reviewCount: 387,
    category: "beach",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    includes: ["Flights", "Private villa", "Yoga sessions", "Temple tours"],
    maxGroupSize: 14,
    featured: false,
    badge: null,
  },
  {
    id: 7,
    title: "Nepal Everest Trek",
    description: "Climb the world's highest peak and experience trekking in the Himalayas",
    destination: "Nepal",
    duration: "14 Days / 13 Nights",
    price: 25000,
    originalPrice: 32000,
    currency: "EGP",
    rating: 5.0,
    reviewCount: 95,
    category: "adventure",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800",
    includedTrips: [1, 3],
    gallery: [
      "https://images.unsplash.com/photo-1522083115901-bc11d2449b29?w=800"
    ],
    includes: ["Flights", "Camping accommodation", "Climbing equipment", "Certified mountain guide"],
    maxGroupSize: 8,
    featured: false,
    badge: "Adventurers Only",
  },
  {
    id: 8,
    title: "Japan Cherry Blossom",
    description: "Witness pink cherry blossoms and discover Japan's blend of modernity and tradition",
    destination: "Japan",
    duration: "11 Days / 10 Nights",
    price: 27000,
    originalPrice: 33000,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 256,
    category: "city",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
    includes: ["Flights", "Traditional Ryokan hotel", "JR Pass", "Cultural tours"],
    maxGroupSize: 18,
    featured: false,
    badge: "Seasonal",
  },
];

export const mockCategories = [
  { id: "all", label: "All", icon: "Globe" },
  { id: "beach", label: "Beaches", icon: "Waves" },
  { id: "mountain", label: "Mountains", icon: "Mountain" },
  { id: "city", label: "Cities", icon: "Building" },
  { id: "adventure", label: "Adventure", icon: "Compass" },
];

export const mockStats = {
  destinations: 120,
  travelers: 50000,
  years: 15,
  rating: 4.9,
};
