export const mockTrips = [
  {
    id: 1,
    title: "رحلة شرم الشيخ الساحرة",
    titleEn: "Enchanting Sharm El-Sheikh Trip",
    description: "استمتع بأجمل شعاب مرجانية وغطس في مياه البحر الأحمر الصافية",
    descriptionEn: "Enjoy the most beautiful coral reefs and diving in crystal clear Red Sea waters",
    destination: "شرم الشيخ، مصر",
    destinationEn: "Sharm El-Sheikh, Egypt",
    duration: "5 أيام",
    durationEn: "5 Days",
    price: 4500,
    currency: "EGP",
    rating: 4.8,
    reviewCount: 892,
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800",
    gallery: [
      "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=800",
      "https://images.unsplash.com/photo-1534008897995-27a23e859048?w=800",
      "https://images.unsplash.com/photo-1519046904884-53103b34b7a9?w=800",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800"
    ],
    type: "beach",
    typeEn: "Beach",
    departureDate: "2024-08-15",
    availableSeats: 8,
    totalSeats: 20,
    highlights: ["غطس في الشعاب المرجانية", "رحلة قوارب", "وليمة بحرية"],
    highlightsEn: ["Coral reef diving", "Boat trip", "Seafood feast"],
    difficulty: "سهل",
    difficultyEn: "Easy",
    guide: "أحمد محمد",
    guideEn: "Ahmed Mohamed",
    meetingPoint: "مارينا الغردقة الرئيسي - بوابة 2",
    meetingPointEn: "Hurghada Marina Main - Gate 2",
    included: ["تأجير معدات الغطس", "وجبة غداء بحرية", "مشروبات طوال اليوم", "مدرب معتمد"],
    includedEn: ["Snorkeling gear rental", "Seafood lunch", "Drinks all day", "Certified instructor"],
    excluded: ["الانتقالات من وإلى الفندق", "صور فوتوغرافية"],
    excludedEn: ["Hotel transfers", "Photography"],
    requirements: ["إجادة السباحة الأساسية", "ملابس بحر مريحة"],
    requirementsEn: ["Basic swimming skills", "Comfortable swimwear"],
    faqs: [
      { q: "هل الرحلة مناسبة للأطفال؟", a: "نعم، للأطفال فوق 6 سنوات مع وجود مرافق." },
      { q: "ماذا لو كان الجو سيئاً؟", a: "يتم استرداد المبلغ بالكامل أو تأجيل الرحلة ليوم آخر." }
    ],
    faqsEn: [
      { q: "Is the trip suitable for children?", a: "Yes, for children over 6 years with an adult." },
      { q: "What if the weather is bad?", a: "Full refund or reschedule to another day." }
    ]
  },
  {
    id: 2,
    title: "سفاري الصحراء الكبرى",
    titleEn: "Great Desert Safari",
    description: "مغامرة لا تُنسى في رمال الصحراء وتحت نجوم السماء المفتوحة",
    descriptionEn: "An unforgettable adventure in the desert sands under open sky stars",
    destination: "الصحراء الغربية، مصر",
    destinationEn: "Western Desert, Egypt",
    duration: "3 أيام",
    durationEn: "3 Days",
    price: 2800,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 445,
    image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
    gallery: [
      "https://images.unsplash.com/photo-1509316962299-6e3e5b15ce80?w=800",
      "https://images.unsplash.com/photo-1473172081575-b6d310beafbe?w=800",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1451337511055-05f78d411baf?w=800"
    ],
    type: "adventure",
    typeEn: "Adventure",
    departureDate: "2024-09-01",
    availableSeats: 5,
    totalSeats: 12,
    highlights: ["ركوب الجمال", "مخيم تحت النجوم", "جولة الواحات"],
    highlightsEn: ["Camel riding", "Camp under the stars", "Oasis tour"],
    difficulty: "متوسط",
    difficultyEn: "Medium",
    guide: "سمير عبدالله",
    guideEn: "Sameer Abdullah",
    meetingPoint: "مخيم سفاري الواحات البحرية",
    meetingPointEn: "Bahariya Oasis Safari Camp",
    included: ["سيارات دفع رباعي", "خيم مجهزة", "وجبتي إفطار وعشاء", "مرشد صحراوي"],
    includedEn: ["4x4 vehicles", "Equipped tents", "Breakfast & dinner", "Desert guide"],
    excluded: ["المصروفات الشخصية"],
    excludedEn: ["Personal expenses"],
    requirements: ["ملابس قطنية خفيفة", "نظارات شمسية وحذاء رياضي"],
    requirementsEn: ["Light cotton clothes", "Sunglasses and sports shoes"],
    faqs: [
      { q: "هل المخيم آمن؟", a: "نعم، مؤمن بالكامل ومجهز بكل سبل الراحة والأمان." }
    ],
    faqsEn: [
      { q: "Is the camp safe?", a: "Yes, fully secured and equipped with all comfort and safety measures." }
    ]
  },
  {
    id: 3,
    title: "استكشاف الأهرامات والتاريخ",
    titleEn: "Pyramids & History Exploration",
    description: "جولة شاملة في روائع الحضارة المصرية القديمة وأسرارها",
    descriptionEn: "A comprehensive tour of ancient Egyptian civilization wonders and secrets",
    destination: "الجيزة والقاهرة، مصر",
    destinationEn: "Giza & Cairo, Egypt",
    duration: "4 أيام",
    durationEn: "4 Days",
    price: 3200,
    currency: "EGP",
    rating: 4.7,
    reviewCount: 1203,
    image: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=800",
    gallery: [
      "https://images.unsplash.com/photo-1507394944820-e0f9260f2eef?w=800",
      "https://images.unsplash.com/photo-1537595634577-fc784d85822e?w=800",
      "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800",
      "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=800"
    ],
    type: "cultural",
    typeEn: "Cultural",
    departureDate: "2024-08-20",
    availableSeats: 15,
    totalSeats: 25,
    highlights: ["الأهرامات والتمثال", "المتحف المصري", "خان الخليلي"],
    highlightsEn: ["Pyramids & Sphinx", "Egyptian Museum", "Khan El-Khalili"],
    difficulty: "سهل",
    difficultyEn: "Easy",
    guide: "منى سعيد",
    guideEn: "Mona Said",
    meetingPoint: "ميدان التحرير - أمام المتحف المصري",
    meetingPointEn: "Tahrir Square - In front of Egyptian Museum",
    included: ["تذاكر الدخول", "مرشد سياحي", "وجبة غداء"],
    includedEn: ["Entry tickets", "Tour guide", "Lunch"],
    excluded: ["التسوق الشخصي"],
    excludedEn: ["Personal shopping"],
    requirements: ["ملابس مريحة", "كاميرا تصوير"],
    requirementsEn: ["Comfortable clothes", "Camera"],
    faqsEn: []
  },
  {
    id: 4,
    title: "جزيرة سوما باي الخلابة",
    titleEn: "Picturesque Soma Bay Island",
    description: "جنة على الأرض في البحر الأحمر مع أجمل المنتجعات الفاخرة",
    descriptionEn: "Paradise on Earth at the Red Sea with the finest luxury resorts",
    destination: "الغردقة، مصر",
    destinationEn: "Hurghada, Egypt",
    duration: "6 أيام",
    durationEn: "6 Days",
    price: 6800,
    currency: "EGP",
    rating: 4.9,
    reviewCount: 367,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    gallery: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
      "https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
      "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=800"
    ],
    type: "beach",
    typeEn: "Beach",
    departureDate: "2024-09-10",
    availableSeats: 4,
    totalSeats: 16,
    highlights: ["ريف كورال", "رياضات مائية", "سبا فاخر"],
    highlightsEn: ["Coral Reef", "Water sports", "Luxury spa"],
    difficulty: "سهل",
    difficultyEn: "Easy",
    guide: "ريم الأنصاري",
    guideEn: "Reem Al-Ansari",
    meetingPoint: "مطار الغردقة الدولي - صالة الوصول",
    meetingPointEn: "Hurghada International Airport - Arrivals Hall",
    included: ["إقامة شاملة", "رياضات مائية", "جلسة سبا"],
    includedEn: ["All-inclusive stay", "Water sports", "Spa session"],
    excluded: ["الرحلات الإضافية"],
    excludedEn: ["Extra excursions"],
    requirements: ["ملابس سباحة", "واقي شمس"],
    requirementsEn: ["Swimwear", "Sunscreen"],
    faqsEn: []
  },
  {
    id: 5,
    title: "الأقصر وأسوان التاريخية",
    titleEn: "Historical Luxor & Aswan",
    description: "رحلة عبر الزمن في مدينتي الكرنك وأبو الهول",
    descriptionEn: "A journey through time in the cities of Karnak and the Sphinx",
    destination: "الأقصر وأسوان، مصر",
    destinationEn: "Luxor & Aswan, Egypt",
    duration: "7 أيام",
    durationEn: "7 Days",
    price: 5500,
    currency: "EGP",
    rating: 4.8,
    reviewCount: 678,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800",
      "https://images.unsplash.com/photo-1580409126737-0cf93e22519f?w=800",
      "https://images.unsplash.com/photo-1519441029008-83274609a28f?w=800"
    ],
    type: "cultural",
    typeEn: "Cultural",
    departureDate: "2024-10-01",
    availableSeats: 10,
    totalSeats: 22,
    highlights: ["معبد الكرنك", "أبو سمبل", "رحلة نيلية"],
    highlightsEn: ["Karnak Temple", "Abu Simbel", "Nile cruise"],
    difficulty: "سهل",
    difficultyEn: "Easy",
    guide: "وليد حسن",
    guideEn: "Walid Hassan",
    meetingPoint: "فندق سوفيتيل الأقصر",
    meetingPointEn: "Sofitel Hotel Luxor",
    included: ["تذاكر المعابد", "مرشد متخصص", "وجبات مختارة"],
    includedEn: ["Temple tickets", "Specialized guide", "Selected meals"],
    excluded: ["مشروبات إضافية"],
    excludedEn: ["Extra drinks"],
    requirements: ["ملابس محتشمة لزيارة المعابد"],
    requirementsEn: ["Modest clothes for temple visits"],
    faqsEn: []
  },
  {
    id: 6,
    title: "البحر الميت تجربة فريدة",
    titleEn: "Dead Sea Unique Experience",
    description: "استحم في أملاح البحر الميت واستمتع بتجربة العوم الطبيعية",
    descriptionEn: "Bathe in the Dead Sea salts and enjoy the natural floating experience",
    destination: "الأردن",
    destinationEn: "Jordan",
    duration: "5 أيام",
    durationEn: "5 Days",
    price: 7200,
    currency: "EGP",
    rating: 4.7,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    gallery: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800",
      "https://images.unsplash.com/photo-1528127269322-539801943592?w=800",
      "https://images.unsplash.com/photo-1539768942893-daf53e4482e6?w=800"
    ],
    type: "wellness",
    typeEn: "Wellness",
    departureDate: "2024-09-20",
    availableSeats: 7,
    totalSeats: 18,
    highlights: ["السباحة في البحر الميت", "البتراء الوردية", "عجلون القلعة"],
    highlightsEn: ["Dead Sea swimming", "Petra Rose City", "Ajloun Castle"],
    difficulty: "سهل",
    difficultyEn: "Easy",
    guide: "نادية عمر",
    guideEn: "Nadia Omar",
    meetingPoint: "مطار الملكة علياء - عمان",
    meetingPointEn: "Queen Alia Airport - Amman",
    included: ["فندق 5 نجوم", "وجبات يومية", "جولات سياحية"],
    includedEn: ["5-star hotel", "Daily meals", "Sightseeing tours"],
    excluded: ["تأشيرة الدخول"],
    excludedEn: ["Entry visa"],
    requirements: ["جواز سفر ساري", "ملابس سباحة"],
    requirementsEn: ["Valid passport", "Swimwear"],
    faqsEn: []
  },
];

export const mockTripTypes = [
  { id: "all", label: "الكل", labelEn: "All" },
  { id: "beach", label: "شواطئ", labelEn: "Beach" },
  { id: "adventure", label: "مغامرات", labelEn: "Adventure" },
  { id: "cultural", label: "ثقافية", labelEn: "Cultural" },
  { id: "wellness", label: "علاجية", labelEn: "Wellness" },
];
